version: '3'

services:
  nifi:
    image: apache/nifi
    container_name: nifi
    environment:
      NIFI_WEB_HTTP_PORT: '8443'
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      AUTH: 'ldap'
      KEYSTORE_PATH: '/opt/certs/keystore.jks'
      KEYSTORE_TYPE: 'JKS'
      KEYSTORE_PASSWORD: '${KEYSTORE_PASSWORD}'
      TRUSTSTORE_PATH: '/opt/certs/truststore.jks'
      TRUSTSTORE_TYPE: 'JKS'
      TRUSTSTORE_PASSWORD: '${TRUSTSTORE_PASSWORD}'
      INITIAL_ADMIN_IDENTITY: '${INITIAL_ADMIN_IDENTITY}'
      LDAP_AUTHENTICATION_STRATEGY: 'SIMPLE'
      LDAP_MANAGER_DN: '${LDAP_MANAGER_DN}'
      LDAP_MANAGER_PASSWORD: '${LDAP_MANAGER_PASSWORD}'
      LDAP_USER_SEARCH_BASE: '${LDAP_USER_SEARCH_BASE}'
      LDAP_USER_SEARCH_FILTER: '${LDAP_USER_SEARCH_FILTER}'
      LDAP_IDENTITY_STRATEGY: 'USE_DN'
#      - LDAP_IDENTITY_STRATEGY=USE_USERNAME
      LDAP_URL: 'ldap://ldap.aksw.org'
    ports:
      - 8443:8443
    volumes:
      - './certs:/opt/certs'
    restart: always

