version: '3.3'

services:
  nifi:
    container_name: nifi
    image: apache/nifi:${NIFI_VERSION}
    environment:
      NIFI_WEB_HTTP_PORT: 8443
      NIFI_WEB_PROXY_HOST: 0.0.0.0
      AUTH: ldap
      KEYSTORE_PATH: /opt/certs/keystore.jks
      KEYSTORE_TYPE: JKS
      KEYSTORE_PASSWORD: '${KEYSTORE_PASSWORD}'
      TRUSTSTORE_PATH: /opt/certs/truststore.jks
      TRUSTSTORE_TYPE: JKS
      TRUSTSTORE_PASSWORD: '${TRUSTSTORE_PASSWORD}'
      INITIAL_ADMIN_IDENTITY: '${INITIAL_ADMIN_IDENTITY}'
      LDAP_AUTHENTICATION_STRATEGY: SIMPLE
      LDAP_MANAGER_DN: 'uid=nifi,ou=Accounts,dc=aksw,dc=org'
      LDAP_MANAGER_PASSWORD: '${LDAP_MANAGER_PASSWORD}'
      LDAP_USER_SEARCH_BASE: 'DC=aksw,DC=org'
      LDAP_USER_SEARCH_FILTER: '(|(cn={0})(uid={0}))'
      LDAP_IDENTITY_STRATEGY: USE_DN
      LDAP_URL: 'ldap://ldap.aksw.org'
    volumes:
      - type: bind
        source: ./certs
        target: /opt/certs
      - type: volume
        source: nifi
        target: '/opt/nifi/nifi-${NIFI_VERSION}'
    restart: always
    network_mode: host
    ports: 
      - '${NIFI_PORT_PUBLISHED}:8443'

volumes:
  nifi:
