version: '2.1'

services:

  nifi:
#    extends:
#      file: docker-compose.base.yml
#      service: lgd-db-base
#    build: ./lgd-db
    image: apache/nifi
    container_name: nifi
    environment:
      - KEYSTORE_PATH=/opt/certs/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=changeit
      - TRUSTSTORE_PATH=/opt/certs/truststore.jks
      - TRUSTSTORE_PASSWORD=changeit
      - TRUSTSTORE_TYPE=JKS
      - AUTH=ldap
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - INITIAL_ADMIN_IDENTITY=cn=Claus Stadler,ou=People,dc=aksw,dc=org
      - LDAP_MANAGER_DN=cn=admin,uid=nifi,ou=Accounts,dc=aksw,dc=org
      - LDAP_MANAGER_PASSWORD=1apachenifi2
      - LDAP_USER_SEARCH_BASE=uid=nifi,ou=Accounts,dc=aksw,dc=org
      - LDAP_USER_SEARCH_FILTER=cn={0}
      - LDAP_IDENTITY_STRATEGY=USE_DN
      - LDAP_URL=ldap://ldap.aksw.org
    ports:
      - 8014:8080
      - 8443:8443
    volumes:
      - ./target/certs:/opt/certs
#      - /opt/certs:./target/certs
#      - lgd-db-vol:/var/lib/postgresql/data
    restart: always
#    networks:
#      - lgd-net

