version: '3.3'

services:
  nifi:
    container_name: nifi
    image: apache/nifi:${NIFI_VERSION}
    env_file:
      - .env
    volumes:
      - type: bind
        source: /tmp/nar
        target: /opt/nifi/nar
        read_only: true
      - type: bind
        source: ./certs
        target: /opt/certs
        read_only: true
      - type: volume
        source: nifi
        target: '${NIFI_BASE_DIR}/nifi-${NIFI_VERSION}'
    networks:
      - nifi
    restart: always
    ports: 
      - '${NIFI_WEB_HTTPS_PORT}:${NIFI_WEB_HTTPS_PORT}'

  nifi-registry:
    container_name: nifi-registry
    image: apache/nifi-registry:${NIFI_REGISTRY_VERSION}
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./certs
        target: /opt/certs
        read_only: true
      - type: volume
        source: nifi-registry
        target: '/opt/nifi-registry/nifi-registry-${NIFI_REGISTRY_VERSION}'
    networks:
      - nifi
    ports: 
      - '${NIFI_REGISTRY_WEB_HTTPS_PORT}:${NIFI_REGISTRY_WEB_HTTPS_PORT}'

volumes:
  nifi:
  nifi-registry:

networks:
  nifi:
    external: true

