version: '3.3

services:
  nifi:
    container_name: nifi
    image: apache/nifi:${NIFI_VERSION}
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./nars/nifi-hive3-nar-1.7.1.nar
        target: '${NIFI_BASE_DIR}/nifi-${NIFI_VERSION}/lib/1.nar'
        read_only: true
      - type: bind
        source: ./nars/nifi-mongodb-services-nar-1.6.0.nar
        target: '${NIFI_BASE_DIR}/nifi-${NIFI_VERSION}/lib/2.nar'
        read_only: true
      - type: bind
        source: ./certs
        target: /opt/certs
        read_only: true
      - type: volume
        source: nifi-data
        target: '${NIFI_BASE_DIR}/data'
      - type: volume
        source: nifi-flowfile_repository
        target: '${NIFI_BASE_DIR}/flowfile_repository'
      - type: volume
        source: nifi-content_repository
        target: '${NIFI_BASE_DIR}/content_repository'
      - type: volume
        source: nifi-provenance_repository
        target: '${NIFI_BASE_DIR}/provenance_repository'
      - type: volume
        source: nifi
        target: '${NIFI_BASE_DIR}/nifi-${NIFI_VERSION}'
    restart: always
    network_mode: host
    ports: 
      - '${NIFI_WEB_HTTPS_PORT}:${NIFI_WEB_HTTPS_PORT}'

  nifi-registry:
    container_name: nifi-registry
    image: apache/nifi-registry:${NIFI_REGISTRY_VERSION}
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./certs
        target: /opt/certs
        read_only: true
      - type: volume
        source: nifi-registry
        target: '/opt/nifi-registry/nifi-registry-${NIFI_REGISTRY_VERSION}'
    network_mode: host
    ports: 
      - '${NIFI_REGISTRY_WEB_HTTPS_PORT}:${NIFI_REGISTRY_WEB_HTTPS_PORT}'

volumes:
  nifi:
  nifi-data:
  nifi-flowfile_repository:
  nifi-content_repository:
  nifi-provenance_repository:
  nifi-registry:
